package domain

import "time"

// Document represents a single source code file ingested from the repository.
type Document struct {
	ID        string
	FilePath  string
	Content   string
	Language  string
	Chunks    []Chunk
	UpdatedAt time.Time
}

// Chunk represents a semantic segment of a Document (e.g., a function)
type Chunk struct {
	ID         string
	DocumentID string
	Content    string
	StartLine  int
	EndLine    int
	Embedding  []float32
	Metadata   map[string]string
}

// Query represents a user's question to the Semantic Search Agent
type Query struct {
	Text      string
	Embedding []float32
	TopK      int
}

// AgentResponse represents the final explanation generated by the LLM
type AgentResponse struct {
	Answer         string
	RetrievedItems []Chunk
}
